### ISSUE TITLE
Only 5000 Entries visible

### ISSUE THREAD

**Issue by rvrtester** [mapbender/data-manager#2]
If you implement the Example configuration (from the main page), the application shows only 5000 Entries in the left Table, even if the database table has many more rows.

Because these 5000 Entries are the first ones of the database table, the last inserted Entry isn't visible for viewing and editing.

Changing the values for _pageLength: 12_ and _paging: true_ has no effect of the number of 5000 Entries.

**Comment by eSlider** [comment]
@rvrtester, please setup `maxResults` option to the value you need. 
Yes, the element isn't fully described yet.

**Comment by eSlider** [comment]
@rvrtester , `pageLength` option is only for paging the results in the visible element table and with the `paging` option you can switch the paging.
